### PR TITLE
Enable GC64 by default

### PR DESCRIPTION
**Pull request by ghost**
NEEDFIX: Dunno how to do it for 64 bit builds only.

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
This makefile is not used by OpenXRay, so changing it won't give any effect.

**Comment by ghost** [comment]
> This makefile is not used by OpenXRay, so changing it won't give any effect.

But it's used from root makefile: https://github.com/OpenXRay/LuaJIT/blob/6c6f9bb0a26226fb7ce99f6d2d6880f63bf78261/Makefile#L113

**Comment by Xottab-DUTY** [comment]
> But it's used from root makefile

Root makefile neither used.

The real file used is [luajit.cmake](https://github.com/OpenXRay/xray-16/blob/xd_dev/Externals/luajit.cmake).

**Comment by ghost** [comment]
Okay, thank you.

In short: the game was constantly segfaulting, I got tired and ran it under GDB. Apparently, the segfault occurred on a lua_cpcall. I googled it: this is an ancient LuaJIT bug (more precisely, a "feature" with 32-bit addressing even on 64-bit platforms) - LuaJIT doesn't have enough free memory.

Enabling GC64 (already found out, this only affects 64 bit platforms) will fix this problem.

**Pull request closed without merging**
